apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: info-server
  name: info-server
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: info-server
  type: LoadBalancer
status:
  loadBalancer: {}
