name: Apps deploy
on:
  workflow_dispatch
env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-west6-a
  # ACTIONS_ALLOW_UNSECURE_COMMANDS: true  
jobs:
  setup-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
        export_default_credentials: true
    
    - run: |-
        echo $GKE_CLUSTER
        echo $GKE_ZONE
        gcloud auth list
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE
        
    - name: Deploy
      run: |-        
        kubectl apply -k .